name: FBGEMMCI

on:
  push:
    branches:
      - B400
  pull_request:
    branches:
      - B400

jobs:
  build1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Build static FBGEMM lib
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        echo "INSTALL NINJA:"
        pip install ninja
        which ninja
        mkdir build_static
        cd build_static
        echo "STARTING CMAKE"
        cmake -G Ninja -DFBGEMM_BUILD_BENCHMARKS=OFF -DFBGEMM_LIBRARY_TYPE=static -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_CXX_COMPILER="cl.exe" ..
        ninja all
        echo "Build Success"

    - name: Test static FBGEMM lib
      shell: cmd
      run: |
        echo %cd%
        cd build_static
        test\Im2ColFusedRequantizeTest.exe
        if errorlevel 1 exit /b 1



